// Generated by https://quicktype.io

export interface DashboardSummaryResponse {
  numberOfOrders: number;
  paidOrders: number;
  notPaidOrders: number;
  numberOfClient: number;
  numberOfProducts: number;
  productsWithNoInventory: number;
  lowInventory: number;
}
